apiVersion: v1alpha1
kind: Setting

metadata:
    name: plugin-blog-hao-setting

spec:
    forms:
      - group: slideConfig
        label: 幻灯片
        formSchema:
          - $formkit: radio
            name: enableSlide
            key: enableSlide
            id: enableSlide
            label: 是否启用幻灯片功能
            value: false
            help: "仅文章页面和独立页面生效"
            options:
              - label: 启用
                value: true
              - label: 禁用
                value: false
          - $formkit: select
            if: $get(enableSlide).value
            name: themeName
            label: 幻灯片的主题风格
            value: "black"
            options:
              - label: "暗黑风格"
                value: black
              - label: "天空"
                value: sky
              - label: "纯白"
                value: white
              - label: "夜晚"
                value: night
              - label: "白色对比度（逐字标题）"
                value: white_contrast_compact_verbatim_headers
              - label: "简约"
                value: simple
              - label: "血之霓裳"
                value: blood
              - label: "月球"
                value: moon
              - label: "德古拉"
                value: dracula
              - label: "米色"
                value: beige
              - label: "black-contrast"
                value: black-contrast
              - label: "灰白质感"
                value: league
              - label: "serif"
                value: serif
              - label: "浅黄曝光风"
                value: solarized
              - label: "白色对比度"
                value: white-contrast
          - $formkit: group
            if: $get(enableSlide).value
            name: slidePlugin
            label: 插件
            value:
              enablePlugin:
                - pluginName: "RevealMarkdown"
                - pluginName: "RevealHighlight"
            children:
              - $formkit: repeater
                name: enablePlugin
                id: enablePlugin
                max: 6
                label: 启用的插件
                help: "如果为选择使用该插件，则不会出现对应的效果"
                children:
                  - $formkit: select
                    name: pluginName
                    id: pluginName
                    key: pluginName
                    label: "插件列表"
                    options:
                      - value: "RevealMarkdown"
                        label: Markdown编辑幻灯片
                      - value: "RevealHighlight"
                        label: 代码语法高亮
                      - value: "RevealMath.KaTeX"
                        label: 呈现数学方程式
                      - value: "RevealSearch"
                        label: CTRL+Shift+F 搜索幻燈片內容
                      - value: "RevealNotes"
                        label: 单独视窗中显示演讲者视图
                      - value: "RevealZoom"
                        label: Alt + 点击元素放大
          - $formkit: group
            if: $get(enableSlide).value
            name: individualization
            label: 个性化配置
            value:
              mouseWheel: false
              loop: false
              scrollView: false
              scrollProgress: auto
            children:
              - $formkit: radio
                name: mouseWheel
                key: mouseWheel
                id: mouseWheel
                label: "启用鼠标滚轮进行幻灯片预览"
                value: false
                options:
                  - label: 启用
                    value: true
                  - label: 禁用
                    value: false
              - $formkit: radio
                name: loop
                key: loop
                id: loop
                label: "是否自动循环播放幻灯片"
                value: false
                options:
                  - label: 启用
                    value: true
                  - label: 禁用
                    value: false
              - $formkit: radio
                name: scrollView
                key: scrollView
                id: scrollView
                label: "滚动视图"
                value: false
                options:
                  - label: 启用
                    value: true
                  - label: 禁用
                    value: false
              - $formkit: select
                if: $get(scrollView).value
                name: scrollProgress
                label: "滚动条类型"
                value: auto
                help: "复制文本与附加内容的分离方式"
                options:
                  - label: "滚动显示 闲置隐藏"
                    value: auto
                  - label: "始终显示"
                    value: true
                  - label: "始终隐藏"
                    value: false

      - group: copyAdd
        label: "复制追加"
        formSchema:
          - $formkit: textarea
            name: copyAddContent
            label: "追加内容"
            value: "请遵循站内知识共享协议,出处：#url；站点：#site"
            rows: 5
            help: "在站点内复制内容会在其后附加自定义的内容，支持的占位符：#url 当前页面url、#site 站点域名"
          - $formkit: select
            name: divideType
            label: "分割类型"
            value: space
            help: "复制文本与附加内容的分离方式"
            options:
              - label: "空格"
                value: space
              - label: "横线 ---"
                value: line
              - label: "空行"
                value: emptyLine
          - $formkit: number
            name: copyMinLength
            label: "免除追加的字数"
            value: 10
            help: "复制文本字数小于等于免除追加字数将不会添加内容，若小于等于0则对所有复制文本添加内容"
          - $formkit: radio
            name: contentPageOnly
            key: contentPageOnly
            id: contentPageOnly
            label: "仅文章页面和独立页面生效"
            value: false
            help: "启用后则只对文章页面、独立页面复制时追加内容，否则所有内容复制时追加内容,如果主题开启了Pjax，请禁用此选项，否则pjax的缓存会导致功能无法生效！"
            options:
              - label: 启用
                value: true
              - label: 禁用
                value: false

      - group: miniTools
        label: 小工具
        formSchema:
          - $formkit: group
            name: contentSpace
            label: 内容的中英文、符号之间自动添加空格
            value:
              enableContentSpace: false
              scanContent:
            children:
              - $formkit: radio
                name: enableContentSpace
                key: enableContentSpace
                id: enableContentSpace
                help: 是否启用
                value: false
                options:
                  - label: 启用
                    value: true
                  - label: 禁用
                    value: false
              - $formkit: textarea
                if: $get(enableContentSpace).value
                label: 内容的中英文、符号之间自动添加空格
                name: scanContent
                value: "pangu.spacingElementByTagName('body');"
                rows: 3
                help: 写法参考 https://github.com/vinta/pangu.js
          - $formkit: group
            name: contentIndent
            label: 文本内容首行缩进
            help: 开启后则在段落的首行缩进两个空格
            value:
              enableContentIndent: false
              indentNodeName:
            children:
              - $formkit: radio
                name: enableContentIndent
                key: enableContentIndent
                id: enableContentIndent
                help: 是否启用
                value: false
                options:
                  - label: 启用
                    value: true
                  - label: 禁用
                    value: false
              - $formkit: text
                if: $get(enableContentIndent).value
                label: 文章内容缩进的节点类名或者ID名
                name: postIndentNodeName
                value: "#post"
                help: 根据自己使用的主题文章节点选择要适配的内容节点
              - $formkit: text
                if: $get(enableContentIndent).value
                label: 单页面内容缩进的节点类名或者ID名
                name: pageIndentNodeName
                value: "#page"
                help: 根据自己使用的主题单页面节点选择要适配的内容节点
              - $formkit: select
                if: $get(enableContentIndent).value
                name: isOnlyPostIndent
                id: isOnlyPostIndent
                key: isOnlyPostIndent
                label: 是否仅针对文章页面生效
                value: globalPage
                options:
                  - value: onlyPost
                    label: 仅针对文章页面
                  - value: globalPage
                    label: 所有页面
              - $formkit: repeater
                if: $get(enableContentIndent).value
                id: excludeNodeList
                key: excludeNodeList
                name: excludeNodeList
                label: 排除缩进的一些元素
                help: 比如一些图片元素被包裹在p标签里，那么就填写img，对其进行排除或者排除p标签内含有某个类名、id名的属性
                value: [ ]
                max: 12
                min: 0
                children:
                  - $formkit: text
                    name: nodeName
                    value:
                    label: 排除的节点名称
          - $formkit: group
            name: colorless
            label: 站点失色
            help: 开启后则会让站点变为灰色
            value:
              enableColorless: false
              colorlessScope: false
              selfCloseAt:
            children:
              - $formkit: radio
                name: enableColorless
                key: enableColorless
                id: enableColorless
                label: 是否开启
                value: false
                options:
                  - value: true
                    label: 开启
                  - value: false
                    label: 关闭
              - $formkit: radio
                name: colorlessScope
                if: $get(enableColorless).value
                label: 作用范围
                value: false
                options:
                  - value: true
                    label: 全站
                  - value: false
                    label: 仅首页
              - $formkit: date
                name: selfCloseAt
                if: $get(enableColorless).value
                label: 到期自动关闭

